### ISSUE TITLE
Many issues in python script

### ISSUE THREAD

**Issue by JeremyCrookshank** [ItsIgnacioPortal/XSStrike-Reborn#7]
You have many issues in the main xsstrike.py script.

eg:

https://github.com/ItsIgnacioPortal/XSStrike-Reborn/blob/master/xsstrike.py#L201

https://github.com/ItsIgnacioPortal/XSStrike-Reborn/blob/master/xsstrike.py#L206

https://github.com/ItsIgnacioPortal/XSStrike-Reborn/blob/master/xsstrike.py#L91

gave me issues too, is this for py2 or py3?

**Comment by yusuf0x73** [comment]
It's normal, it seems like the author merged the pr's without checking them
